export const BUSINESS_CONFIG = {
  name: "Sai Shraddha Tours & Travels",
  tradeName: "Sai Shraddha Rent A Car",
  ownerName: "Ramesh Shep",
  ownerRole: "Owner, Sai Shraddha Tours & Travels",
  establishedYear: 2014,
  experienceYears: new Date().getFullYear() - 2014,
  tagline: "Serving Customers Since 2014",
  address: "Sai Ashram (Bhakta Niwas 1000 Rooms), Shirdi - 423 109, Maharashtra, India",
  officeLocationName: "Sai Ashram Bhakta Niwas, Shirdi",
  city: "Shirdi",
  state: "Maharashtra",
  pincode: "423109",
  contacts: [
    {
      name: "Ramesh Shep",
      role: "Owner & Operations",
      primaryPhone: "+91 98900 73081",
      primaryPhoneRaw: "919890073081",
      isPrimaryForWhatsApp: true,
    },
  ],
  primaryPhone: "+91 98900 73081",
  primaryPhoneRaw: "919890073081",
  whatsapp: "+91 98900 73081",
  whatsappRaw: "919890073081",
  email: "contact@saishraddhatravels.com",
  locationCoordinates: {
    lat: 19.7667,
    lng: 74.4764,
  },
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
};

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "Services", href: "/services" },
  { label: "Taxi Routes", href: "/routes" },
  { label: "Destinations", href: "/destinations" },
  { label: "Packages", href: "/packages" },
  { label: "Fleet", href: "/fleet" },
  { label: "Reviews", href: "/reviews" },
  { label: "About Us", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const TRUST_FACTORS = [
  {
    title: "Serving Shirdi Since 2014",
    description: "Over a decade of genuine offline experience welcoming devotees, families, and tourists to Shirdi.",
    icon: "ShieldCheck",
  },
  {
    title: "Owned Ertiga & Tavera Fleet",
    description: "We directly own and maintain our core 3 × Maruti Ertiga and 1 × Tavera vehicles for pristine cleanliness and safety.",
    icon: "Car",
  },
  {
    title: "Local Driver Knowledge",
    description: "Courteous local drivers who know every temple route, darshan queue timing, and the fastest safe highways.",
    icon: "MapPin",
  },
  {
    title: "Direct Owner Contact",
    description: "Speak directly with Ramesh Shep (Owner). Honest quotes with zero hidden middleman aggregator charges.",
    icon: "PhoneCall",
  },
];

export const CORE_SERVICES = [
  {
    id: "shirdi-local-taxi",
    title: "Shirdi Local Taxi & Sightseeing",
    slug: "shirdi-local-taxi",
    shortDescription: "Temple pickups, Sai Ashram transfers, hotel drops, and full-day / half-day local Shirdi cabs.",
    icon: "Car",
    highlights: [
      "Sai Baba Samadhi Temple & Dwarkamai transfers",
      "Sai Ashram / Bhakta Niwas pickups",
      "Khandoba Mandir & Shani Shingnapur link",
      "Clean, air-conditioned comfortable cabs",
    ],
  },
  {
    id: "outstation-taxi",
    title: "Outstation Cab Service",
    slug: "outstation-taxi",
    shortDescription: "Reliable one-way and round-trip outstation journeys across Maharashtra with experienced highway drivers.",
    icon: "Navigation",
    highlights: [
      "Direct highway trips via Samruddhi Mahamarg",
      "Nashik, Pune, Mumbai, Aurangabad & beyond",
      "Door-to-door doorstep pickup and drop",
      "Transparent per-km and fixed package rates",
    ],
  },
  {
    id: "airport-railway-transfers",
    title: "Airport & Railway Station Transfers",
    slug: "airport-railway-transfers",
    shortDescription: "Punctual transfers for Shirdi Airport (Kakadi), Sainagar Shirdi Railway Station, Manmad Junction, Pune & Mumbai airports.",
    icon: "Plane",
    highlights: [
      "Shirdi Airport (SAG) 24/7 dedicated cabs",
      "Manmad Junction & Kopargaon train pickups",
      "Pune (PNQ) & Mumbai (BOM) airport transfers",
      "Luggage assistance & flight timing monitoring",
    ],
  },
  {
    id: "pilgrimage-tours",
    title: "Pilgrimage & Darshan Tours",
    slug: "pilgrimage-tours",
    shortDescription: "Spiritual darshan tours covering Shani Shingnapur, Trimbakeshwar Jyotirlinga, Grishneshwar, and Maharashtra Jyotirlingas.",
    icon: "Compass",
    highlights: [
      "Patient, unhurried pacing for elderly devotees",
      "Guidance on temple darshan timings & passes",
      "Combined same-day & multi-day spiritual circuits",
      "Customised family yatra itineraries",
    ],
  },
  {
    id: "group-transportation",
    title: "Group Transportation & Tempo Travellers",
    slug: "group-transportation",
    shortDescription: "Spacious 13, 17, and 20-seater Tempo Travellers, mini-buses, and coaches for yatra groups and large families.",
    icon: "Users",
    highlights: [
      "Pushback luxury reclining seats with AC",
      "Dedicated overhead and rear luggage capacity",
      "Music system and charging points",
      "Ideal for Bhajan mandals, sanghas & yatris",
    ],
  },
  {
    id: "corporate-wedding-travel",
    title: "Corporate, Wedding & Event Travel",
    slug: "corporate-wedding-travel",
    shortDescription: "Multi-vehicle fleet coordination for Shirdi weddings, destination events, corporate group yatras, and conferences.",
    icon: "Briefcase",
    highlights: [
      "Multi-cab fleet dispatch and coordination",
      "VIP sedan and luxury SUV options on request",
      "Dedicated on-ground travel manager in Shirdi",
      "Transparent billing and quotation receipts",
    ],
  },
];

export const POPULAR_DESTINATIONS = [
  {
    name: "Shirdi to Shani Shingnapur",
    slug: "shirdi-to-shani-shingnapur",
    distanceKm: 72,
    approxTravelTime: "1.5 - 2 hrs",
    startingFare: 1800,
    shortDescription: "The most sought-after pilgrimage day-trip from Shirdi to the self-manifested Shani Bhagwan temple.",
    highlights: ["Doorstep hotel/ashram pickup", "Direct highway drive", "Flexible waiting time for darshan"],
  },
  {
    name: "Shirdi to Nashik & Trimbakeshwar",
    slug: "shirdi-to-nashik-trimbakeshwar",
    distanceKm: 115,
    approxTravelTime: "2.5 - 3 hrs",
    startingFare: 2600,
    shortDescription: "Visit the revered Trimbakeshwar Jyotirlinga, Kushavarta Tirtha, Panchavati, Sita Gufa, and Muktidham.",
    highlights: ["Trimbakeshwar Jyotirlinga Darshan", "Kalaram & Goraram Mandir", "Ramkund & Godavari Ghats"],
  },
  {
    name: "Shirdi to Aurangabad, Grishneshwar & Ellora Caves",
    slug: "shirdi-to-aurangabad-ellora",
    distanceKm: 110,
    approxTravelTime: "2.5 - 3 hrs",
    startingFare: 2800,
    shortDescription: "Grishneshwar Jyotirlinga, the world-wonder Kailash Temple at Ellora Caves, Bhadra Maruti, and Bibi Ka Maqbara.",
    highlights: ["12th Jyotirlinga Grishneshwar", "UNESCO World Heritage Ellora Caves", "Bhadra Maruti Temple"],
  },
  {
    name: "Shirdi to Pune (City / Airport)",
    slug: "shirdi-to-pune",
    distanceKm: 200,
    approxTravelTime: "4 - 4.5 hrs",
    startingFare: 3800,
    shortDescription: "Smooth one-way and roundtrip cab transfers connecting Shirdi directly with Pune city, railway station, and airport.",
    highlights: ["Direct highway route", "Doorstep drops in Pune", "Toll receipt clarity"],
  },
  {
    name: "Shirdi to Mumbai (City / Airport)",
    slug: "shirdi-to-mumbai",
    distanceKm: 240,
    approxTravelTime: "4.5 - 5 hrs via Samruddhi Mahamarg",
    startingFare: 4500,
    shortDescription: "Express highway travel from Shirdi to Mumbai, Thane, Navi Mumbai, and Chhatrapati Shivaji Maharaj International Airport.",
    highlights: ["Samruddhi Mahamarg express drive", "24/7 airport drops", "Comfortable rest stops"],
  },
  {
    name: "Shirdi to Ajanta Caves",
    slug: "shirdi-to-ajanta-caves",
    distanceKm: 210,
    approxTravelTime: "4.5 - 5 hrs",
    startingFare: 4800,
    shortDescription: "Full-day historical excursion to the world-famous 2nd-century BCE rock-cut Buddhist monument caves at Ajanta.",
    highlights: ["Ancient Buddhist rock-cut caves", "Expert highway driver", "Full-day sightseeing tour"],
  },
  {
    name: "Shirdi to Bhimashankar Jyotirlinga",
    slug: "shirdi-to-bhimashankar",
    distanceKm: 185,
    approxTravelTime: "4 - 4.5 hrs",
    startingFare: 3800,
    shortDescription: "Scenic pilgrimage journey into the Sahyadri mountains to darshan at the holy Bhimashankar Jyotirlinga.",
    highlights: ["Holy Jyotirlinga in Western Ghats", "Scenic Sahyadri mountain drive", "Safe, experienced hill drivers"],
  },
  {
    name: "Shirdi to Vani (Saptashrungi Devi)",
    slug: "shirdi-to-vani-saptashrungi",
    distanceKm: 140,
    approxTravelTime: "3.5 hrs",
    startingFare: 3200,
    shortDescription: "Sacred Shaktipeeth pilgrimage to the seven-peaked mountain abode of Goddess Saptashrungi Nivasini.",
    highlights: ["One of the 51 Shaktipeeths", "Mountain ropeway access point", "Comfortable family cab travel"],
  },
];

export const PILGRIMAGE_PACKAGES = [
  {
    id: "nashik-trimbakeshwar-darshan",
    title: "Nashik & Trimbakeshwar Darshan",
    slug: "nashik-trimbakeshwar-darshan",
    duration: "1 Day (8 - 10 Hours)",
    destinationsSummary: "Trimbakeshwar • Muktidham • Panchavati • Sita Gufa • Ramkund • Kalaram",
    startingFare: 2600,
    shortDescription: "Full darshan of the ancient Trimbakeshwar Jyotirlinga and holy sights of Nashik referenced since our earliest visiting cards.",
    placesCovered: [
      "Trimbakeshwar Jyotirlinga & Kushavarta Tirtha",
      "Muktidham Temple Complex",
      "Panchavati & Sita Gufa (Caves)",
      "Kalaram Mandir & Goraram Mandir",
      "Ramkund & Godavari Triveni Sangam",
      "Kapaleshwar Mahadev Mandir",
    ],
    idealFor: "Families & pilgrims wanting complete Nashik holy darshan in one smooth day.",
  },
  {
    id: "aurangabad-ellora-grishneshwar",
    title: "Aurangabad, Ellora & Grishneshwar Darshan",
    slug: "aurangabad-ellora-grishneshwar",
    duration: "1 Day (9 - 11 Hours)",
    destinationsSummary: "Grishneshwar Jyotirlinga • Ellora Caves • Bhadra Maruti • Bibi Ka Maqbara",
    startingFare: 2800,
    shortDescription: "Experience the divine 12th Jyotirlinga at Grishneshwar, the legendary sleeping Hanuman at Bhadra Maruti, and the architectural wonder of Ellora Caves.",
    placesCovered: [
      "Grishneshwar Jyotirlinga (12th Jyotirlinga)",
      "Ellora Caves (Kailash Rock-Cut Temple)",
      "Bhadra Maruti Sleeping Hanuman Mandir (Khuldabad)",
      "Bibi Ka Maqbara (Historical monument)",
      "Daulatabad Fort (Sightseeing on request)",
    ],
    idealFor: "Devotees seeking combined Jyotirlinga darshan and world heritage exploration.",
  },
  {
    id: "shani-shingnapur-day-tour",
    title: "Shani Shingnapur Same-Day Darshan",
    slug: "shani-shingnapur-day-tour",
    duration: "Half Day (4 - 5 Hours)",
    destinationsSummary: "Shirdi • Shani Shingnapur • Return to Shirdi",
    startingFare: 1800,
    shortDescription: "The essential spiritual complement to your Shirdi Sai Baba darshan. Dedicated trip to the open-air Swayambhu Shani temple.",
    placesCovered: [
      "Doorstep pickup from your Shirdi hotel or Sai Ashram",
      "Smooth 72 km drive via state highway",
      "Oil offering (Telabhishekam) assistance at Shani Shingnapur",
      "Direct return drop back to Shirdi temple or railway station",
    ],
    idealFor: "Every pilgrim visiting Shirdi who wishes to seek Shani Dev's blessings.",
  },
  {
    id: "maharashtra-5-jyotirlinga-circuit",
    title: "5 Maharashtra Jyotirlinga Custom Circuit",
    slug: "maharashtra-5-jyotirlinga-circuit",
    duration: "4 - 5 Days Custom Yatra",
    destinationsSummary: "Trimbakeshwar • Grishneshwar • Bhimashankar • Aundha Nagnath • Parli Vaijnath",
    startingFare: null, // Custom quote
    shortDescription: "A grand pilgrimage covering all five holy Jyotirlinga shrines in Maharashtra, planned with patient driving and restful overnight halts.",
    placesCovered: [
      "Trimbakeshwar (Nashik)",
      "Grishneshwar (Ellora)",
      "Bhimashankar (Pune Hills)",
      "Aundha Nagnath (Hingoli)",
      "Parli Vaijnath (Beed)",
      "Includes Shirdi Sai Baba Darshan base",
    ],
    idealFor: "Devout family groups, senior citizens, and spiritual yatra groups.",
  },
  {
    id: "special-destinations-circuit",
    title: "Western Maharashtra Special Tours",
    slug: "special-destinations-circuit",
    duration: "Custom Multi-Day Tours",
    destinationsSummary: "Pandharpur • Vani (Saptashrungi) • Mahabaleshwar • Lonavala • Khandala",
    startingFare: null, // Custom quote
    shortDescription: "Customized outstation tour packages connecting Shirdi with major pilgrimage centers and Western Ghats scenic hill stations.",
    placesCovered: [
      "Pandharpur Vitthal Rukmini Darshan",
      "Vani Saptashrungi Mata Shaktipeeth",
      "Mahabaleshwar & Panchgani Hill Tours",
      "Lonavala & Khandala Ghat Sightseeing",
      "Mumbai & Pune pickup and drop connectivity",
    ],
    idealFor: "Extended family holidays and custom Maharashtra holiday circuits.",
  },
];

export const FLEET_INFO = {
  owned: [
    {
      name: "Maruti Suzuki Ertiga (3 Vehicles)",
      category: "6+1 Seater Premium SUV/MUV",
      seating: "6 Passengers + Driver",
      luggage: "3-4 Suitcases",
      ac: "Dual AC with Rear Vents",
      fuel: "CNG / Diesel",
      description: "Our flagship owned vehicles since 2014. Regularly sanitized, highly comfortable with ample legroom for family pilgrimages, airport transfers, and long highway journeys.",
      idealFor: "Families, senior citizens, airport pickups, Nashik & outstation trips",
      isOwned: true,
    },
    {
      name: "Chevrolet Tavera (1 Vehicle)",
      category: "7+1 / 8+1 Seater Spacious MUV",
      seating: "7-8 Passengers + Driver",
      luggage: "4-5 Large Suitcases",
      ac: "Powerful Roof-Mounted AC",
      fuel: "Diesel",
      description: "Owned high-capacity MUV offering maximum cabin space, robust suspension, and generous luggage room for larger joint families and group pilgrimages.",
      idealFor: "Large families, luggage-heavy outstation tours, temple circuits",
      isOwned: true,
    },
  ],
  network: [
    {
      name: "Sedans (Swift Dzire / Toyota Etios)",
      category: "4+1 Seater Compact Sedan",
      seating: "4 Passengers + Driver",
      luggage: "2-3 Suitcases",
      description: "Available subject to confirmation through our verified local driver network. Smooth, economical travel for couples and small families.",
      isOwned: false,
    },
    {
      name: "Tempo Travellers (13, 17, 20 Seaters)",
      category: "Group Luxury Van",
      seating: "12 to 20 Passengers + Driver",
      luggage: "Dedicated luggage carrier & boot",
      description: "Pushback luxury seats, dual AC, music system, and charging sockets for medium-sized pilgrimage groups and family gatherings.",
      isOwned: false,
    },
    {
      name: "Mini Buses & Large Coaches (22 - 53 Seaters)",
      category: "Group Tour Bus",
      seating: "22 to 53 Passengers",
      luggage: "Large underbelly storage hold",
      description: "Arranged on request with verified experienced commercial drivers for yatra sanghas, wedding guest shuttles, and corporate yatras.",
      isOwned: false,
    },
    {
      name: "Luxury & Specialized Vehicles",
      category: "Premium On-Demand",
      seating: "Varies by model",
      luggage: "As per vehicle",
      description: "Innova Crysta, luxury sedans, and specialized vehicles available upon prior reservation for VIP guests and events.",
      isOwned: false,
    },
  ],
};
